CREATE TABLE [dbo].[CUSTOMERS](
	[CUSTOMER_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMAIL_ADDRESS] [nvarchar](255) NOT NULL,
	[FULL_NAME] [nvarchar](255) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMERS] ADD PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[CUSTOMERS] ADD UNIQUE NONCLUSTERED 
(
	[EMAIL_ADDRESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[ORDERS](
	[ORDER_ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDER_TMS] [datetime] NOT NULL,
	[CUSTOMER_ID] [int] NOT NULL,
	[ORDER_STATUS] [varchar](50) NOT NULL,
	[STORE_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDERS] ADD PRIMARY KEY CLUSTERED 
(
	[ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDERS] ADD  DEFAULT (getdate()) FOR [ORDER_TMS]
GO
ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Customers] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMERS] ([CUSTOMER_ID])
GO
ALTER TABLE [dbo].[ORDERS] CHECK CONSTRAINT [FK_Orders_Customers]
GO
